---
# tasks file for mapr_hbaseregionserver

- name: install mapr-hbase-regionserver
  become: yes
  become_user: root
  yum: name=mapr-hbase-regionserver-{{hbase_version}}.{{hbase_build}} state=present
  environment: '{{proxy_env}}'
  when: inventory_hostname in groups["regionserver"]
